USE reclutamiento_ocr;
SHOW TABLES;

SELECT 
    TABLE_NAME AS tabla,
    COLUMN_NAME AS campo,
    REFERENCED_TABLE_NAME AS tabla_referenciada,
    REFERENCED_COLUMN_NAME AS campo_referenciado
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'reclutamiento_ocr'
AND REFERENCED_TABLE_NAME IS NOT NULL;